function [ para ] = fun_0_5_ofFiles( para, cam_id, per_id )
%FUN_0_5_OFFILES Summary of this function goes here
%   Detailed explanation goes here

if nargin == 1
	para.files.EName = [...
		'-' para.of.color...
		'-C' num2str(para.of.channels)...
		'-D' num2str(para.of.FrameDelta)...
		'-L' num2str(para.of.lb)...
		'-M' num2str(para.of.mode)];
	para.files.indexName = [para.files.EName...
		'-G' num2str(para.of.GaussionSize)...
		'-F' num2str(para.of.fft_f)];
else
	para.files.EName = [...
		'-cam' cam_id '-per' per_id...
		'-' para.of.color...
		'-C' num2str(para.of.channels)...
		'-D' num2str(para.of.FrameDelta)...
		'-L' num2str(para.of.lb)...
		'-M' num2str(para.of.mode)];
	para.files.indexName = [para.files.EName...
		'-G' num2str(para.of.GaussionSize)...
		'-F' num2str(para.of.fft_f)];
end

para.files.EFile = [para.dir.saveOfEnergy '\OfEnergy' para.files.EName '.mat'];
para.files.indexFile = [para.dir.saveOfResults '\OfFilt' para.files.indexName '.mat'];

end

