function Hd = my_hamming_filter
%HAMMING_FILTER Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.14 and the Signal Processing Toolbox 6.17.
%
% Generated on: 08-Aug-2013 11:22:14
%

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 30;  % Sampling Frequency

N    = 511;      % Order
Fc1  = 0.5;      % First Cutoff Frequency
Fc2  = 1.5;        % Second Cutoff Frequency
flag = 'scale';  % Sampling Flag
% Create the window vector for the design algorithm.
win = hamming(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
Hd = dsp.FIRFilter( ...
    'Numerator', b);

% [EOF]
